### ISSUE TITLE
博主你好 points下面没有训练和测试数据

### ISSUE THREAD

**Issue by suyunzzz** [YhQIAO/PointCloudSVMDemo#1]

**Comment by canhetingyu** [comment]
这个文件夹里的数据是什么格式呢

**Comment by suyunzzz** [comment]
> 这个文件夹里的数据是什么格式呢
什么格式都行

**Comment by canhetingyu** [comment]
> > 这个文件夹里的数据是什么格式呢
> > 什么格式都行

 你已经运行了是吗

**Comment by suyunzzz** [comment]
> > > 这个文件夹里的数据是什么格式呢
> > > 什么格式都行
> 
> 你已经运行了是吗

对的，你自己做数据就行，不需要很多

**Comment by canhetingyu** [comment]
作者提供的那个文件夹是没数据还是

**Comment by canhetingyu** [comment]
> > > > 这个文件夹里的数据是什么格式呢
> > > > 什么格式都行
> > 
> > 
> > 你已经运行了是吗
> 
> 对的，你自己做数据就行，不需要很多

您能分享一下数据吗
